algoritmo "AconselhaPrograma"
// Função :
// Autor :
// Data : 25/11/2024
// Seção de Declarações 
var
   Dinheiro: real
inicio
// Seção de Comandos
   Escreva("Quanto de dinheiro você tem sobrando?")
   Leia(dinheiro)
   Se dinheiro >= 10 entao
      Escreval("Vá ao cinema hoje")
   Senao
        Escreval("Fique em casa olhando tv")
   fimse
        Escreva("Obrigado volte sempre")
fimalgoritmo
